services:
    Ruwler\SdkBundle\Service\RuwlerService:
        arguments:
            $apiKey: '%ruwler_sdk.api_key%'
            $options: {auth_mode: '%ruwler_sdk.auth_mode%', host: '%ruwler_sdk.host%', timeout: '%ruwler_sdk.timeout%', debug: '%ruwler_sdk.debug%', format: '%ruwler_sdk.format%'}
